# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Notte < Formula
  desc "Browser automation CLI for notte.cc"
  homepage "https://notte.cc"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nottelabs/notte-cli/releases/download/v0.0.1/notte-cli_0.0.1_darwin_amd64.tar.gz"
      sha256 "4e1939179bc950dbc8c0466f28aa51655f8ade9b3017051315bcabc3d390aa04"

      def install
        bin.install "notte"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nottelabs/notte-cli/releases/download/v0.0.1/notte-cli_0.0.1_darwin_arm64.tar.gz"
      sha256 "58a789f6a00997f39d40b9123ff5dd177e8b0714e2690775f3d5a82c91e21fef"

      def install
        bin.install "notte"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nottelabs/notte-cli/releases/download/v0.0.1/notte-cli_0.0.1_linux_amd64.tar.gz"
      sha256 "61f3af73dfd27dac49b5a9cb21e8ba451dfa1fd10c6a48c1113f7889ff32d8e3"
      def install
        bin.install "notte"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nottelabs/notte-cli/releases/download/v0.0.1/notte-cli_0.0.1_linux_arm64.tar.gz"
      sha256 "1cc3eeaba9a60db196fa499194bd61a037f16ecd94d3232b9abfc489a81e5d7f"
      def install
        bin.install "notte"
      end
    end
  end

  test do
    system "#{bin}/notte", "version"
  end
end
